package com.self.Exceptions

object Exception2 {

}